name: flutter_frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.9.0

dependencies:
    flutter:
        sdk: flutter
    flutter_svg: ^2.2.0
    mask_text_input_formatter: ^2.9.0
    provider: ^6.1.5+1
    signalr_netcore: ^1.4.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - lib/assets/
        - lib/assets/images/
        - lib/assets/fonts/
    fonts:
        - family: "Lexend"
          fonts:
              - asset: lib/assets/fonts/lexend.ttf
